chore: run presubmit test sequentially (#3952)

diff --git a/.kokoro/templates/trampoline.sh.erb b/.kokoro/templates/trampoline.sh.erb
--- a/.kokoro/templates/trampoline.sh.erb
+++ b/.kokoro/templates/trampoline.sh.erb
@@ -25,7 +25,13 @@ function cleanup() {
 
 cd $REPO_DIR
 
-versions=(2.3.8 2.4.5 2.5.5 2.6.3)
+versions=(<%= ruby_versions.join " " %>)
+
+# Capture failures
+EXIT_STATUS=0 # everything passed
+function set_failed_status {
+    EXIT_STATUS=1
+}
 
 STARTTIME=$(date +%s)
 
@@ -34,17 +40,24 @@ if [[ $JOB_TYPE = "presubmit" ]]; then
     if [[ $COMMIT_MESSAGE = *"[ci skip]"* || $COMMIT_MESSAGE = *"[skip ci]"* ]]; then
         echo "[ci skip] found. Exiting"
     elif [[ $OS = "windows" ]]; then
-            python "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}"
+            python "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}" || set_failed_status
     else
-        python3 "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}" $version
+        for version in "${versions[@]}"; do
+            (
+                python3 "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}" $version || set_failed_status
+            ) &
+        done
+        wait
     fi
 else
     if [[ $OS = "windows" ]]; then
-        python "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}"
+        python "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}" || set_failed_status
     else
-        python3 "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}"
+        python3 "${KOKORO_GFILE_DIR}/${TRAMPOLINE_SCRIPT}" || set_failed_status
     fi
 fi
 
 ENDTIME=$(date +%s)
 echo "Tests took a total of $(($ENDTIME - $STARTTIME)) seconds"
+
+exit $EXIT_STATUS
